services:
  diplom_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diplom_frontend
    ports:
      - "8080:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - diplom_network

networks:
  diplom_network:
    driver: bridge