"""init

Revision ID: aacfd8f4a440
Revises: 
Create Date: 2026-02-24 13:13:27.465153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacfd8f4a440'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like_bus_id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('name_ua', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('ukrpas_id', sa.Integer(), nullable=True),
    sa.Column('inbus_id', sa.BigInteger(), nullable=True),
    sa.Column('rubikon_id', sa.Integer(), nullable=True),
    sa.Column('voyager_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False, comment='Currency code (e.g. DZD)'),
    sa.Column('rate', sa.Float(), nullable=False, comment='Exchange rate value'),
    sa.Column('exchange_date', sa.Date(), nullable=True, comment='Date of exchange rate update'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_parsed', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_city_id', sa.Integer(), nullable=False),
    sa.Column('to_city_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_routes_from_to_date', 'routes', ['from_city_id', 'to_city_id', 'departure_date'], unique=False)
    op.create_index(op.f('ix_routes_created_at'), 'routes', ['created_at'], unique=False)
    op.create_index(op.f('ix_routes_departure_date'), 'routes', ['departure_date'], unique=False)
    op.create_index(op.f('ix_routes_from_city_id'), 'routes', ['from_city_id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_parsed_at'), 'routes', ['parsed_at'], unique=False)
    op.create_index(op.f('ix_routes_site_id'), 'routes', ['site_id'], unique=False)
    op.create_index(op.f('ix_routes_to_city_id'), 'routes', ['to_city_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('from_station', sa.String(), nullable=True),
    sa.Column('to_station', sa.String(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('carrier_name', sa.String(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('is_transfer', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_arrival_date'), 'trips', ['arrival_date'], unique=False)
    op.create_index(op.f('ix_trips_carrier_name'), 'trips', ['carrier_name'], unique=False)
    op.create_index(op.f('ix_trips_created_at'), 'trips', ['created_at'], unique=False)
    op.create_index(op.f('ix_trips_departure_time'), 'trips', ['departure_time'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_is_transfer'), 'trips', ['is_transfer'], unique=False)
    op.create_index(op.f('ix_trips_route_id'), 'trips', ['route_id'], unique=False)
    op.create_table('trip_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_history_created_at'), 'trip_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_trip_history_id'), 'trip_history', ['id'], unique=False)
    op.create_index(op.f('ix_trip_history_trip_id'), 'trip_history', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_history_trip_id'), table_name='trip_history')
    op.drop_index(op.f('ix_trip_history_id'), table_name='trip_history')
    op.drop_index(op.f('ix_trip_history_created_at'), table_name='trip_history')
    op.drop_table('trip_history')
    op.drop_index(op.f('ix_trips_route_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_is_transfer'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_departure_time'), table_name='trips')
    op.drop_index(op.f('ix_trips_created_at'), table_name='trips')
    op.drop_index(op.f('ix_trips_carrier_name'), table_name='trips')
    op.drop_index(op.f('ix_trips_arrival_date'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_routes_to_city_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_site_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_parsed_at'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_from_city_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_departure_date'), table_name='routes')
    op.drop_index(op.f('ix_routes_created_at'), table_name='routes')
    op.drop_index('idx_routes_from_to_date', table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
