"""update city class

Revision ID: dc6c63e293c6
Revises: aacfd8f4a440
Create Date: 2026-02-24 13:41:55.634496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6c63e293c6'
down_revision: Union[str, None] = 'aacfd8f4a440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'name_ru')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('name_ru', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
