version: '3.8'

services:
  diplom_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diplom_worker
    restart: always
    env_file:
      - .env
    command: >
      bash -c "
         celery -A parser.app.settings.celery_app worker --concurrency=1 -Q high_priority --loglevel=info --hostname=worker.high_priority@%h &
         celery -A parser.app.settings.celery_app worker --autoscale=25,7 -Q parsing --loglevel=info --hostname=worker.parsing@%h
      "
    volumes:
      - .:/code/parser
    networks:
      - diplom_network

  diplom_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diplom_beat
    restart: always
    env_file:
      - .env
    command: celery -A parser.app.settings.celery_app beat --loglevel=info
    volumes:
      - .:/code/parser
    networks:
      - diplom_network

  diplom_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diplom_app
    env_file:
      - .env
    depends_on:
      - diplom_worker
      - diplom_beat
    volumes:
      - .:/code/parser
    networks:
      - diplom_network
    command: bash -c "cd parser && alembic upgrade head"

networks:
  diplom_network:
    driver: bridge
